---
sudo: false
language: ruby
cache: bundler
env:
matrix:
  include:
    - rvm: jruby-1.7.25
    - rvm: jruby-1.7.25
      env: LOGSTASH_BRANCH=master
    - rvm: jruby-1.7.25
      env: LOGSTASH_BRANCH=5.x
    - rvm: jruby
      env: LOGSTASH_BRANCH=feature/jruby-9k
  allow_failures:
    - rvm: jruby
  fast_finish: true
install:
script: ci/build.sh

jdk: oraclejdk8
